accounts/urls.py
from django.conf.urls import url
from .views import (register_view,login_view,logout_view)
urlpatterns = [
   
	url(r'^register/$', register_view, name='register'),   
	url(r'^login/$', login_view, name='login'),
	url(r'^logout/$', logout_view, name='logout'),
	]

chatbot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
#from django.contrib.auth.views import login, logout
from chat.views import index,message_to_all
from chat.api.views import index_api

urlpatterns = [
    url(r'^$', index ,name='index'),#home page
	url(r'^broadcast/$', message_to_all, name='broadcast'),
    url(r'^accounts/', include("accounts.urls",namespace='users')),
    url(r'^admin/', admin.site.urls),

    url(r'^api/test/$', index_api, name='jwt-test'),#for testing chat using jwt
    url(r'^api/accounts/', include("accounts.api.urls",namespace='users-api')),
    url(r'^api/chat/', include("chat.api.urls",namespace='chat-api')),
]

#on production static files should be separet from other django files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

templates/base.html
<!DOCTYPE html>

{% load static from staticfiles %}

<html>
<head>
    <title>{% block title %}ChatBot{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  	<link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
  	<link rel="stylesheet" href="{% static 'css/chat.css' %}">
</head>
<body>
	
<div class="container">
  <ol class="breadcrumb">
    <li><a href="{%url 'index' %}">Home</a></li>
    {%if request.user.is_staff or request.user.is_superuser %}
    <li><a href="{%url 'broadcast' %}">broadcast</a></li>
    <li><a href="{%url 'jwt-test' %}?token=">jwt test</a></li>
    {%endif%}
    {%if not request.user.is_authenticated%}
    <li class="pull-right"><a href="{%url 'users:register'%}">Register</a></li>     
    <li class="pull-right"><a href="{%url 'users:login'%}">Login</a></li>
    {%else%}  
    <li class="pull-right"><a href="{%url 'users:logout'%}">Logout</a></li> 
    {%endif%}
  </ol>
</div>
	<div class="section">
    	<div class="container">
      		{% block content %}{% endblock content %}
    	</div>
  	</div>  
  	{% block afterbody %}{% endblock afterbody %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
  {% load static from staticfiles %}
  <h1>Chatbot</h1>
  <form id="chatform">
    <table id="chat">
      <tbody>
        {% for message in messages %}
          <tr>
            <td>{{ message.owner }}</td>
            <td>{{ message.formatted_timestamp }}</td>
            <td>{{ message.user }}</td>
            <td>{{ message.message }}</td>
          </tr> 
        {% endfor %}
      </tbody>
      <tfoot>
      <tr>
        <td>Say something:</td>
        <td colspan=2>
          <input id="message" type="text" placeholder="message">
          </td>
          <td>
          Character:
          <select id="mySelect">
            <option value=0 >general</option>
            <option value=1 >action</option>
            <option value=2>animation</option>
            <option value=3>comedy</option>
            <option value=4>crime</option>
            <option value=5>drama</option>
            <option value=6>fantasy</option>
            <option value=7>filmnoir</option>
            <option value=8>horror</option>
            <option value=9>romance</option>
            <option value=10>scifi</option>
            <option value=11>war</option>
          </select>
          <button class="btn btn-primary" type="submit" id="go">Say it</button>
          </td>
      </tfoot>
    </table>
  </form>
{% endblock content %}

{% block afterbody %}
  <script type="text/javascript" src='{% static "js/jquery-1.12.1.min.js" %}'></script>
  <script type="text/javascript" src='{% static "js/reconnecting-websocket.min.js" %}'></script>
  <script type="text/javascript" src='{% static "js/chat.js" %}'></script>
{% endblock afterbody %}

templates/messages_display.html
{% if messages %}
	<div class="messages">
		<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message}}
		</li>
		{% endfor %}
		</ul>
	</div>
{% endif %}